### ISSUE TITLE
Wrong method used

### ISSUE THREAD

**Issue by Arman-Hosseini** [knpuniversity/symfony2-rest#20]
Course: https://symfonycasts.com/screencast/symfony-rest2/httpexception-invalid-json
The $em->persist method in updateAction was used to update the entity and should be deleted.

**Comment by Arman-Hosseini** [comment]
And the entity will not be updated.
Only a new one is created.

**Comment by MolloKhan** [comment]
Hey @Arman-Hosseini 

You are totally right. On updates you don't need call `persist()` (although, it doesn't do any harm)

**Comment by bocharsky-bw** [comment]
Thank you for this report @Arman-Hosseini ! As @larzuk91 mentioned, it's ok to call `persist()` when "update" entities, it just does nothing. And since we're showing it in the video, and we do want our code matches the video - it just does not worth to be deleted, too much work. So, I'm closing this, but feel free to remove that call in your own code.
